### PR TITLE
install expect dependency

### LINKED ISSUE #13: Cannot login to npm
When deploying project and trying to log into npm here's the output

```
Deploying project into Node.js runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /package.json
Installing node 7.4.0
Installing npm 4.1.1
/usr/bin/env: expect: No such file or directory
Build attempt failed, attempting again.
```

### PR DESCRIPTION
**Pull request by theworkflow**
Installs the `expect` dependency. This is needed to log into npm via `npm-login`

Closes #13

### CODE REVIEW

File: bootstrap.sh [hunk 1]
```diff
@@ -8,6 +8,9 @@ export TEMP_DIR=/tmp
 export TMPDIR=/tmp
 export TMP_DIR=/tmp
 
+# install expect
+apt-get install -y expect
```
Comment (jackboberg) [inline bootstrap.sh:12]: `apt-get update &&`

Comment (theworkflow) [reply bootstrap.sh:12]: Is there a reason for the `update`? Local tests don't require that. Also if I do I will also have to do `autoremove`

Comment (jackboberg) [reply bootstrap.sh:12]: assume it's been done elsewhere then, default ubuntu install seems to require that (for me)

**Review by jackboberg — APPROVED** [review]
